project:
  type: website
  output-dir: docs

website:
  title: "MIDFIELD Institute"
  page-navigation: true
  page-footer:
    center:
      - text: "License"
        href: license.qmd
  reader-mode: true
  repo-url: https://github.com/MIDFIELDR/2024-midfield-institute
  repo-actions: [issue]
  favicon: figures/logo.png
  back-to-top-navigation: true
  navbar:
    background: primary
    right:
      - icon: git
        href: https://github.com/MIDFIELDR/2024-midfield-institute
  comments:
    utterances:
      repo: https://github.com/MIDFIELDR/2024-midfield-institute
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Welcome"
        file: index.qmd

      - text: "Introduction"
        file: introduction.qmd

      - text: "Before you arrive"
        file: before-you-arrive.qmd

      - text: "Program"
        file: agenda.qmd

      - section: "Tutorial links"
        file: tutorials.qmd
        contents:
          - r-basics.qmd
          - chart-basics.qmd
          - data-basics.qmd
          - text: Case study goals
            url: https://midfieldr.github.io/midfieldr/articles/art-001-case-goals.html
          - text: Case study data
            url: https://midfieldr.github.io/midfieldr/articles/art-002-case-data.html
          - text: Case study results
            url: https://midfieldr.github.io/midfieldr/articles/art-003-case-results.html
          - text: Post-workshop tutorials
            url: https://midfieldr.github.io/midfieldr/articles/

      - section: "Shaping data 3 ways"
        contents:
          - text: "Introduction"
            file: data-shaping-00-introduction.qmd
          - data-shaping-01-data-selection.qmd
          - data-shaping-02-basic-transforms.qmd
          - data-shaping-03-aggregating-transforms.qmd
          - data-shaping-04-multi-table-transforms.qmd
          - data-shaping-05-reshaping-transforms.qmd

      - text: "Resources"
        file: r-resources.qmd

      - text: "License"
        file: license.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    code-link: true
    code-copy: true
    code-overflow: wrap
    fig-cap-location: bottom
    tbl-cap-location: top
    reference-location: margin




