project:
  type: website
  output-dir: docs

website:
  title: "MIDFIELD Institute"
  page-navigation: true
  page-footer:
    center:
      - text: "License"
        href: license.qmd
  reader-mode: true
  repo-url: https://github.com/MIDFIELDR/2023-midfield-institute
  repo-actions: [issue]
  favicon: figures/logo.png
  navbar:
    background: primary
    right:
      - icon: git
        href: https://github.com/MIDFIELDR/2023-midfield-institute
  comments:
    utterances:
      repo: https://github.com/MIDFIELDR/2023-midfield-institute
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Welcome"
        file: index.qmd

      - text: "License"
        file: license.qmd



format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    code-copy: true



