{
  "hash": "46ecc6b63484f9170e1c0b1d844aede4",
  "result": {
    "markdown": "---\ntitle: \"R basics\"\n---\n\n\n![](figures/logo-R.png)\n\n\n\n\n\n\n\n\nAn introduction to key concepts in R. \n\n[License.]{.important} This material is adapted from *Getting started in R: Tinyverse edition* by Bashir and Eddelbuettel [-@Bashir+Eddelbuettel:2018] which was licensed under CC BY-SA by [ilustat](https://ilustat.com/post/writing-real-life-motivated-r-guides/). This adaptation and extension, *R basics* by Richard Layton, is licensed under [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/legalcode). \n\n## Preface\n\nThis guide gives you a flavor of what R can do for you. To get the most out of this guide, do the examples and exercises as you read along.\n\n[Experiment safely.]{.important} Be brave and experiment with commands and options as it is an essential part of the learning process. Things can and will go \"wrong\", like getting error messages or deleting things that you create. You can recover from most situations using \"undo\" `ctrl Z` (MacOS `cmd Z`) or restarting R with the RStudio menu *Session \\> Restart R*.\n\n[Before starting.]{.important} Our tutorials assume that you\n\n- Have completed the [Before you arrive](before-you-arrive.html) instructions\\\n- Start your R session by launching the RStudio project you created, e.g., `midfield-institute-2023.Rproj`\n\nIf you are in an RStudio project, the project name appears in the upper left corner of the RStudio window. Your project directory (folder) should look something like this:\n\n    midfield-institute-2023\\\n        data\\\n        results\\\n        scripts\\\n        midfield-institute-2023.Rproj\n\n## Getting started\n\n[Starting R & RStudio.]{.important} R starts automatically when you open RStudio with a screen similar to @fig-pane-layout. \n\n- Source: view and edit files, e.g., R scripts   \n- Console: run lines of code interactively  \n- Environment: display currently saved R objects \n- Output: files, plots, packages, help\n\n\n::: {.cell .fig-cap-location-margin}\n::: {.cell-output-display}\n![RStudio pane layout. See RStudio's User Guide [Pane layout](https://docs.posit.co/ide/user/ide/guide/ui/ui-panes.html) for details on contents and layout editing.](figures/pane-layout.png){#fig-pane-layout width=496}\n:::\n:::\n\n\nThe console starts with information about the version number, license and contributors. The last line is a prompt (`>`) that indicates R is ready to do something.\n\n\n::: {.cell .fig-cap-location-margin}\n::: {.cell-output-display}\n![Console at startup](figures/console-startup.png){#fig-console-startup width=352}\n:::\n:::\n\n\n\n[Quitting R & RStudio]{.important}. When you quit RStudio you will be asked whether to *Save workspace?* with a yes or no option. If you choose *Yes*, your current workspace is restored the next time you open RStudio. But as long as you save your script, saving the workspace is unnecessary. I recommend you choose *No*.\n\nTo set *No* as the default option, from the RStudio menu select *Tools \\> Global Options*.\n\n-   Un-check the box *Restore .RData into workspace at startup*\n-   Set *Save workspace to .RData on exit:* to \"Never\"\n\n\n::: {.cell .fig-cap-location-margin}\n::: {.cell-output-display}\n![RStudio global options default settings.](figures/rstudio-never-workspace.png){#fig-tinyverse-02 width=605}\n:::\n:::\n\n\n## R help\n\nR's built-in help system is an essential part of finding solutions to your R programming problems.\n\n[help() function]{.important}. From the R Console you can use the `help()` function or `?`. For example, try the following two commands (which give the same result):\n\n``` r\n# view the function help page\nhelp(mean)\n? mean\n```\n\nIf you are asking for the package help page (assuming you have installed the package), type in the Console, \n\n``` r\n# view a package help page\nhelp(package = \"midfieldr\")\n```\n\n[Keyword search.]{.important} To do a keyword search use the function `apropos()` with the keyword in double quotes (\"keyword\") or single quote ('keyword'). For example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# keyword search \napropos(\"mean\")\n#>  [1] \".colMeans\"     \".rowMeans\"     \"colMeans\"      \"kmeans\"       \n#>  [5] \"mean\"          \"mean.Date\"     \"mean.default\"  \"mean.difftime\"\n#>  [9] \"mean.POSIXct\"  \"mean.POSIXlt\"  \"rowMeans\"      \"weighted.mean\"\n```\n:::\n\n\nThe lines of R output are labeled---here with `[1]`, `[5]` , and `[9]`. These labels indicate the index or position of the first element in that line within the overall output (here, of length 12). Thus in this output vector, `\".colMeans\"` has index 1, `\"mean\"` has index 5, and `\"mean.POSIXct\"` has index 9.\n\n[Help examples.]{.important} Use the `example()` function to run the examples at the end of the help for a function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run the examples at the end of the help page\nexample(mean)\n#> \n#> mean> x <- c(0:10, 50)\n#> \n#> mean> xm <- mean(x)\n#> \n#> mean> c(xm, mean(x, trim = 0.10))\n#> [1] 8.75 5.50\n```\n:::\n\n\nHere, the output of the `mean()` example has length 2 (8.75 5.50). The label `[1]` indicates that the number 8.75 has index 1. \n\n[RStudio help.]{.important} Rstudio provides search box in the *Help* tab in the *Output pane* to make your life easier (see @fig-pane-layout).\n\n[Online help.]{.important} When you search online use \\[r\\] in your search terms, for example, \"\\[r\\] linear regression\". Because we use data.table for data manipulation, I further recommend that you include data.table as a keyword, e.g., \"\\[r\\]\\[data.table\\] group and summarize\". \n\nThere is nearly always more than one solution to your problem---investigate the different options and try to use one whose arguments and logic you can follow. Limiting your browser's search to the past year can sometimes eliminate out-of-date solutions.\n\n   \n\n::: panel-tabset\n\n## [Exercise 1.1]{.important} \n\nTry the following.\n\n1.  `help(median)`\n2.  `? sd`\n3.  `? max`\n\n## Answer\n\nThe following help pages should appear in the RStudio *Help* pane.\n\n![](figures/r-basics-ans-01.png)\n\n![](figures/r-basics-ans-02.png)\n\n![](figures/r-basics-ans-03.png)\n:::\n\n[Warning.]{.important} If an R command is not complete then R will show a plus sign (`+`) prompt on second and subsequent lines until the command syntax is correct.\n\n``` r\n+ \n```\n\nPress the escape key (ESC) to break out.\n\n[Hint.]{.important} To recall a previous command, put your cursor in the Console and use the up arrow key (↑). To go between previously typed commands use the up and down arrow (↓) keys. To modify or correct a command use the left (←) and right arrow (→) keys.\n\n\n\n## R scripts\n\n[Creating a script]{.important} I recommend that you write your lines of code in a script. Scripts can saved, edited, and run again and again. \n\n- Use *File &gt; New File &gt; R Script* to create a new R script\n- *File &gt; Save As...* to name the file (I suggest `01-r-basics.R`), then save it to the `scripts` directory \n- At the top of the script, add a minimal header, something like: \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# R basics \n# your name \n# date \n```\n:::\n\n\nThe hash symbol `#` denotes a *comment* in R, that is, a line that isn't run. Comments are annotations to make the source code easier for humans to understand but are ignored by R.\n\nNext,  \n\n- Use `library()` to load packages used in the script. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# packages\nlibrary(\"midfieldr\")\n```\n:::\n\n\nNote: In a code chunk like the one above, you can click on the \"Copy to clipboard\" icon in the upper right corner to enable quick copy and paste from this document to your script.\n\n[**Running a script**]{.important}\n\n- Run the script by clicking the *Source* button. Some participants report that this does not always work. The workaround is to: \n- Select the lines you want to run  then *ctrl Enter* (MacOS *cmd Return*). Use the keyboard shortcuts *ctrl A* (MacOS *cmd A*) to select all lines. (See the appendices for a table of useful keyboard shortcuts.)\n\nIf you see an error like this one, \n\n```\n    Error in library(\"midfieldr\"): there is no package called 'midfieldr'\n```\n\nthen you should install the missing package(s) and run the script again. You can review how to install a package [here](before-you-arrive.html#install-cran-packages).  \n\n\nUse your script throughout the tutorial. When a new chunk of code is given,  \n\n- Copy the line(s) of code into your script, save, and run.     \n- Check your result by comparing it to the result in the tutorial.\n- Check what you've learned using the **Your turn** exercises. \n\n## R concepts\n\nIn R speak, scalars, vectors, variables and datasets are called *objects.* To create objects (things) we use the assignment operator (`<-`). \n\nFor example, the object `height` is assigned a value of 173 as follows,\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# assign a value to a named object \nheight <- 173\n```\n:::\n\n\nTyping the name alone prints out its value, \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# view\nheight\n#> [1] 173\n```\n:::\n\n\nIn these notes, everything that comes back to us in the Console as the result of running a script is shown prefaced by `#>`.\n\nObjects in your R project workspace are listed in the RStudio Environment pane. At this point, we have three objects in the environment.  \n\n![](figures/rstudio-environment-x-y.png)\n\n[Warning: R is case sensitive.]{.important} `age` and `AgE` are different:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# illustrating case-sensitivity \nage <- 10\nAgE <- 50\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# display result\nage\n#> [1] 10\nAgE\n#> [1] 50\n```\n:::\n\n\n[New lines.]{.important} R commands are usually separated by a new line but\nthey can also be separated by a semicolon (not recommended). \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# recommended style\nname <- \"Leo\"\nage  <- 25\ncity <- \"Lisbon\"\n\n# views\nname\n#> [1] \"Leo\"\nage\n#> [1] 25\ncity\n#> [1] \"Lisbon\"\n\n# style not recommended \nname <- \"Leo\"; age <- 25; city <- \"Lisbon\"\n\n# view\nname; age; city\n#> [1] \"Leo\"\n#> [1] 25\n#> [1] \"Lisbon\"\n```\n:::\n\n\n[Comments.]{.important} It is useful to put comments in your script---especially useful to the future you looking back at your script after several months.  \n\nR comments start with a hash sign (`#`). Everything after the hash to the end of the line is ignored by R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# This comment line is ignored when run.\n\ncity # text after \"#\" is ignored.\n#> [1] \"Lisbon\"\n```\n:::\n\n\n## R as a calculator\n\nYou can use R as a calculator by typing in the Console. Try the following:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# type in the console\n2 + 3\n#> [1] 5\n\n(5 * 11) / 4 - 7\n#> [1] 6.75\n\n7^3 # exponent\n#> [1] 343\n```\n:::\n\n\n[Other math functions.]{.important} You can also use standard mathematical functions that are typically found on a scientific calculator. \n\n- trigonometric: `sin()`, `cos()`, `tan()`, etc. \n- rounding: `abs()`, `ceiling()`, `floor()`, `round()`, `sign()`,\n`signif()`, `trunc()`\n- logarithms and exponentials: `log()`, `log10()`, `log2()`, `exp()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# type in the console\n\n# square root\nsqrt(2)\n#> [1] 1.414214\n\n# round down to nearest integer\nfloor(8.6178)\n#> [1] 8\n\n# round to 2 decimal places\nround(8.6178, 2)\n#> [1] 8.62\n```\n:::\n\n\n::: panel-tabset\n\n## [Exercise 1.2]{.important} \n\nWhat do the following pairs of examples do?\n\n1. `ceiling(18.33); signif(9488, 2)`\n2. `exp(1); log10(1000)`\n3. `sign(-2.9); sign(32)`\n4. `abs(-27.9); abs(11.9)`\n\n## Answer\n\n1. 19 and 9500 \n2. 2.718 and 3\n3. -1 and 1\n4. 27.9 and 11.9\n:::\n\n\n## More R concepts\n\nFrom this point, please type the R code chunks in your script, save and run, and compare your results to those shown. \n\nYou can do some useful things using the assignment operator (`<-`), for example, \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# assign dimensions\nroom_length <- 7.8\nroom_width  <- 6.4\n\n# compute area\nroom_area <- room_length * room_width\n\n# view\nroom_area\n#> [1] 49.92\n```\n:::\n\n\n[On coding style.]{.important} Summary of commonly used coding styles for naming objects in R include: \n\n|style       |example       |\n|:-----------|:-------------|\n|snake case  | `room_area`  |\n|camel case  | `roomArea`   |\n|Pascal case | `RoomArea`   |\n\nWe use *snake case*, that is, lowercase letters and numbers with words separated by underscores. You may of course use any style you are comfortable with.\n\n[Text objects.]{.important} You can assign text to an object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# assign text to an object\ngreeting <- \"Hello world!\"\n\n# view\ngreeting\n#> [1] \"Hello world!\"\n```\n:::\n\n\n[Vectors.]{.important} The objects presented so far have been scalars (single values). Working with vectors is where R shines best as they are the basic building blocks of datasets. \n\nWe can create a vector using the `c()` (combine values into a vector) function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# a numeric vector\nx1 <- c(26, 10, 4, 7, 41, 19)\n\n# view\nx1\n#> [1] 26 10  4  7 41 19\n\n# a character vector\nx2 <- c(\"Peru\", \"Italy\", \"Cuba\", \"Ghana\")\n\n# view\nx2\n#> [1] \"Peru\"  \"Italy\" \"Cuba\"  \"Ghana\"\n```\n:::\n\n\nThere are many other ways to create vectors, for example, `rep()`\n(replicate elements) and `seq()` (create sequences):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# repeat vector (2, 6, 7, 4) three times\nr1 <- rep(c(2, 6, 7, 4), times = 3)\n\n# view\nr1\n#>  [1] 2 6 7 4 2 6 7 4 2 6 7 4\n\n\n# vector from -2 to 3 incremented by 0.5\ns1 <- seq(from = -2, to = 3, by = 0.5)\n\n# view\ns1\n#>  [1] -2.0 -1.5 -1.0 -0.5  0.0  0.5  1.0  1.5  2.0  2.5  3.0\n```\n:::\n\n\n[Vector operations.]{.important} You can do calculations on vectors, for example using `x1` from above:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# multiply every element by 2\nx1 * 2\n#> [1] 52 20  8 14 82 38\n\n# operation order: product, root, then round\nround(sqrt(x1 * 2.6), 2)\n#> [1]  8.22  5.10  3.22  4.27 10.32  7.03\n```\n:::\n\n\n[Missing values.]{.important} Missing values are coded as `NA` in R. For example,\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# numeric vector with a missing value\nx2 <- c(3, -7, NA, 5, 1, 1)\n\n# view\nx2\n#> [1]  3 -7 NA  5  1  1\n\n# character vector with a missing value\nx3 <- c(\"rat\", NA, \"mouse\", \"hamster\")\n\n# view\nx3\n#> [1] \"rat\"     NA        \"mouse\"   \"hamster\"\n```\n:::\n\n\n[Managing objects.]{.important} Use function `ls()` to list the objects in your\nworkspace. The `rm()` function deletes them. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# view objects in workspace\nls()\n#>  [1] \"age\"             \"AgE\"             \"city\"            \"greeting\"       \n#>  [5] \"has_annotations\" \"height\"          \"name\"            \"r1\"             \n#>  [9] \"room_area\"       \"room_length\"     \"room_width\"      \"s1\"             \n#> [13] \"x\"               \"x1\"              \"x2\"              \"x3\"             \n#> [17] \"xm\"\n\n# remove objects\nrm(x1, x2, x3, r1, s1, AgE, age)\n\n# view result\nls()\n#>  [1] \"city\"            \"greeting\"        \"has_annotations\" \"height\"         \n#>  [5] \"name\"            \"room_area\"       \"room_length\"     \"room_width\"     \n#>  [9] \"x\"               \"xm\"\n```\n:::\n\n\n::: panel-tabset\n\n## [Exercise 1.3]{.important} \n\nAdd the tax to the net amount and round to the nearest integer. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nnet <- c(108.99, 291.42, 16.28, 62.29, 31.77)\ntax <- c(22.89, 17.49, 0.98, 13.08, 6.67)\n```\n:::\n\n\n## Answer\n\n\n::: {.cell}\n\n```\n#> [1] 132 309  17  75  38\n```\n:::\n\n:::\n\n## R functions and packages\n\n[R functions.]{.important} We have already used some R functions (e.g. `c()`, `mean()`, `rep()`, `sqrt()`, `round()`). Most computation in R involves  functions. \n\nA function essentially has a name and a list of arguments separated by commas. For example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# closer look at function arguments\nseq(from = 5, to = 8, by = 0.4)\n#> [1] 5.0 5.4 5.8 6.2 6.6 7.0 7.4 7.8\n```\n:::\n\n\n- the function name is `seq` \n- the function has three arguments `from` (the start value), `to` (the end value), and `by` (the increment between values)\n- arguments are assigned values (using `=`) within the parentheses and are separated by commas\n\nThe `seq()` function has other arguments, documented in the help page. For example, we could use the argument `length.out` (instead of `by`) to fix the length of the sequence as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# replacing `by` with `length.out` \nseq(from = 5, to = 8, length.out = 16)\n#>  [1] 5.0 5.2 5.4 5.6 5.8 6.0 6.2 6.4 6.6 6.8 7.0 7.2 7.4 7.6 7.8 8.0\n```\n:::\n\n\n[Custom functions.]{.important} As you gain familiarity with R, you may want to learn how to construct your own custom functions, but that's not an objective of our \"basics\" tutorials. \n\n[R packages.]{.important} The basic R installation comes with over 2000 functions, but R can be extended further using contributed *packages*. Packages are like \"apps\" for R, containing functions, data, and documentation. \n\nTo see a list of functions and data sets bundled in a package, use the `ls()` function, e,g,\n\n\n::: {.cell}\n\n```{.r .cell-code}\nls(\"package:midfieldr\")\n#>  [1] \"add_completion_status\" \"add_data_sufficiency\"  \"add_timely_term\"      \n#>  [4] \"baseline_mcid\"         \"cip\"                   \"filter_cip\"           \n#>  [7] \"fye_proxy\"             \"order_multiway\"        \"prep_fye_mice\"        \n#> [10] \"same_content\"          \"select_required\"       \"study_observations\"   \n#> [13] \"study_programs\"        \"study_results\"         \"toy_course\"           \n#> [16] \"toy_degree\"            \"toy_student\"           \"toy_term\"\n```\n:::\n\n\nAlternatively, in RStudio select the `Packages` tab and in its menu bar type the package name in the search box. In the pane, click on the package name. A help page opens listing all the functions and names of data sets in the package, e.g., \n\n![](figures/rstudio-package-functions.png)\n\nIn MIDFIELD work, we use a small number of R packages:\n\n- midfieldr for tools to study student unit records\n- midfielddata for practice data \n- data.table for manipulating data \n- ggplot2 for charts \n\n\n\n\n\n## About R objects\n\n[Everything in R has class.]{.important}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(room_area)  # assigned earlier\n#> [1] \"numeric\"\n\nclass(greeting)   # assigned earlier\n#> [1] \"character\"\n\nclass(seq)        # R function \n#> [1] \"function\"\n```\n:::\n\n\nCertain actions will change the class of an object. Suppose we create a vector from the `room_area` and `greeting` objects.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(room_area, greeting)\nx\n#> [1] \"49.92\"        \"Hello world!\"\n\nclass(x)\n#> [1] \"character\"\n```\n:::\n\n\nBy concatenating a number and a character string, R changed the class of room area from \"numeric\" to \"character\" because all elements of a vector must have the same class.\n\n[Data frames.]{.important} The most common class of data object we will use is the *data frame*: a two-dimensional array of rows and columns in R. All values in a column are of the same type (numerical, character, logical, etc.) but columns can be of different types. \n\nFor example, the data frame `study_results` that is bundled with midfieldr has three character columns and three numerical columns. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# a data frame bundled with midfieldr\nstudy_results\n#>     program    sex            race ever_enrolled graduates stickiness\n#>  1:      CE Female           Asian            15        10       66.7\n#>  2:      CE Female           Black             4         1       25.0\n#>  3:      CE Female   International            23        13       56.5\n#>  4:      CE Female          Latine            13         6       46.2\n#>  5:      CE Female Native American             1         1      100.0\n#>  6:      CE Female   Other/Unknown             5         3       60.0\n#>  7:      CE Female           White           263       162       61.6\n#>  8:      CE   Male           Asian            30        25       83.3\n#>  9:      CE   Male           Black             8         5       62.5\n#> 10:      CE   Male   International            97        55       56.7\n#> 11:      CE   Male          Latine            66        31       47.0\n#> 12:      CE   Male Native American             3         1       33.3\n#> 13:      CE   Male   Other/Unknown            27        11       40.7\n#> 14:      CE   Male           White           949       612       64.5\n#> 15:      EE Female           Asian            21        12       57.1\n#> 16:      EE Female           Black             6         3       50.0\n#> 17:      EE Female   International            28         9       32.1\n#> 18:      EE Female          Latine             8         3       37.5\n#> 19:      EE Female Native American             1         0        0.0\n#> 20:      EE Female   Other/Unknown             7         3       42.9\n#> 21:      EE Female           White           118        56       47.5\n#> 22:      EE   Male           Asian           123        71       57.7\n#> 23:      EE   Male           Black            29        17       58.6\n#> 24:      EE   Male   International           195        90       46.2\n#> 25:      EE   Male          Latine            45        17       37.8\n#> 26:      EE   Male Native American             3         0        0.0\n#> 27:      EE   Male   Other/Unknown            42        16       38.1\n#> 28:      EE   Male           White           864       439       50.8\n#> 29:     ISE Female           Asian            15        10       66.7\n#> 30:     ISE Female           Black             7         6       85.7\n#> 31:     ISE Female   International             6         2       33.3\n#> 32:     ISE Female           White            77        54       70.1\n#> 33:     ISE   Male           Asian            24        14       58.3\n#> 34:     ISE   Male           Black             9         6       66.7\n#> 35:     ISE   Male   International            22        12       54.5\n#> 36:     ISE   Male          Latine             6         4       66.7\n#> 37:     ISE   Male           White           187       130       69.5\n#> 38:      ME Female           Asian             7         1       14.3\n#> 39:      ME Female           Black             3         2       66.7\n#> 40:      ME Female   International            19        11       57.9\n#> 41:      ME Female          Latine            12         8       66.7\n#> 42:      ME Female   Other/Unknown             8         4       50.0\n#> 43:      ME Female           White           213       134       62.9\n#> 44:      ME   Male           Asian            76        49       64.5\n#> 45:      ME   Male           Black            30        19       63.3\n#> 46:      ME   Male   International           178        89       50.0\n#> 47:      ME   Male          Latine            79        42       53.2\n#> 48:      ME   Male Native American             5         1       20.0\n#> 49:      ME   Male   Other/Unknown            80        41       51.2\n#> 50:      ME   Male           White          1596       953       59.7\n#>     program    sex            race ever_enrolled graduates stickiness\n\nclass(study_results)\n#> [1] \"data.table\" \"data.frame\"\n```\n:::\n\n\nThe `class()` function reveals that this `data.frame` object is also a `data.table` object, which is an enhanced version of R's standard data frame.\n\n::: {.panel-tabset}\n\n## [Exercise 1.4]{.important} \n\nFor the following midfieldr objects, determine:\n\n- the class of `add_timely_term`\n- the class of `toy_student`\n- the names of the variables in `toy_term`\n\n## Answer\n1. function\n2. data.table, data.frame\n3. mcid, institution, term, cip6, level\n\n\n:::\n\n[Everything in R has structure]{.important}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(room_area)  # assigned earlier\n#>  num 49.9\n\nstr(greeting)         # assigned earlier\n#>  chr \"Hello world!\"\n\nstr(seq)              # R function \n#> function (...)\n\nstr(study_results)\n#> Classes 'data.table' and 'data.frame':\t50 obs. of  6 variables:\n#>  $ program      : chr  \"CE\" \"CE\" \"CE\" \"CE\" ...\n#>  $ sex          : chr  \"Female\" \"Female\" \"Female\" \"Female\" ...\n#>  $ race         : chr  \"Asian\" \"Black\" \"International\" \"Latine\" ...\n#>  $ ever_enrolled: int  15 4 23 13 1 5 263 30 8 97 ...\n#>  $ graduates    : int  10 1 13 6 1 3 162 25 5 55 ...\n#>  $ stickiness   : num  66.7 25 56.5 46.2 100 60 61.6 83.3 62.5 56.7 ...\n#>  - attr(*, \".internal.selfref\")=<externalptr>\n```\n:::\n\n\n\n::: {.panel-tabset}\n\n## [Exercise 1.5]{.important} \n\nUse `str()` to determine \n\n1. `add_timely_term` arguments\n2. `toy_student` dimensions\n3. `study_results` numerical variables\n\n## Answer\n\n\n::: {.cell}\n\n:::\n\n\n1. The `str()` function prints out the arguments and their default values within the parentheses:\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(add_timely_term)\n#> function (dframe, midfield_term = term, ..., span = NULL, sched_span = NULL)\n```\n:::\n\n2. 99 rows and 4 columns\n3. 3 variables: ever_enrolled, graduates, stickiness\n\n:::\n\n\n\n\n## Keyboard shortcuts {.appendix}\n\nIf you are working in RStudio, you can see the menu of keyboard shortcuts using the menu *Tools \\> Keyboard Shortcuts Help*.\n\nThe shortcuts we use regularly include\n\n\n::: {.cell}\n::: {.cell-output-display}\n|Windows / Linux |Action                              |Mac OS         |\n|:---------------|:-----------------------------------|:--------------|\n|`ctrl shift K`  |Compile R Markdown document         |`cmd shift K`  |\n|`ctrl L`        |Clear the RStudio Console           |`ctrl L`       |\n|`ctrl shift C`  |Comment/uncomment line(s)           |`cmd shift C`  |\n|`ctrl X, C, V`  |Cut, copy, paste                    |`cmd X, C, V`  |\n|`ctrl F`        |Find in text                        |`cmd F`        |\n|`ctrl I`        |Indent or re-indent lines od code   |`cmd I`        |\n|`alt` --        |Insert the assignment operator `<-` |`option` --    |\n|`ctrl alt B`    |Run from  begining to line          |`cmd option B` |\n|`ctrl alt E`    |Run from line to end                |`cmd option E` |\n|`ctrl Enter`    |Run selected line(s)                |`cmd Return`   |\n|`ctrl S`        |Save                                |`cmd S`        |\n|`ctrl A`        |Select all text                     |`cmd A`        |\n|`ctrl Z`        |Undo                                |`cmd Z`        |\n:::\n:::\n\n\n## References\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}